sfsh = scale_transformation(OLCEK_MEMNUNIYET_GN_SAG),
sfss = scale_transformation(OLCEK_MEMNUNIYET_ASAYIS),
sfsj = scale_transformation(OLCEK_MEMNUNIYET_ADLI),
sfse = scale_transformation(OLCEK_MEMNUNIYET_EGITI),
sfss = scale_transformation(OLCEK_MEMNUNIYET_SGK),
sfst = scale_transformation(OLCEK_MEMNUNIYET_ULASIM),
sfsg = scale_transformation(ELEKTRO_HIZ),
sfs = (fcoalesce(sfsh, 0) + fcoalesce(sfss, 0) + fcoalesce(sfsj, 0) + fcoalesce(sfse, 0) + fcoalesce(sfss, 0) + fcoalesce(sfst, 0) + fcoalesce(sfsg, 0)) /
  (ifelse(is.na(sfsh), 0, 1) + ifelse(is.na(sfss), 0, 1) + ifelse(is.na(sfsj), 0, 1) +ifelse(is.na(sfse), 0, 1) +ifelse(is.na(sfss), 0, 1) + ifelse(is.na(sfst), 0, 1) + ifelse(is.na(sfsg), 0, 1)) 
sex = gender(CINSIYET),
age = as.numeric(BITIRILEN_YAS),
age2 = as.numeric(BITIRILEN_YAS)^2,
mars = marital_status(MEDENI_DURUM),
edl = education_level(OKUL_BITEN),
emp = employment(CALISMA_DURUM, CALISMAMA_NEDEN, TRUE),
hap = scale_transformation(MUTLULUK),
mat = materialism(NE_MUTLU),
fya = scale_transformation(GECMIS_KARSILASTIRMA, 3, 1),
fyl = scale_transformation(GELECEK_KARSILASTIRMA, 3, 1),
hhi_lvl = scale_transformation(GELIR_GRUP, 1, 5),
hhi_suf = scale_transformation(OLCEK_GELIR_KARSILAMA),
sh = scale_transformation(OLCEK_MEMNUNIYET_SAGLIK),
ms = scale_transformation(OLCEK_MEMNUNIYET_EVLILIK),
eds = scale_transformation(OLCEK_MEMNUNIYET_EGITIM),
hos = scale_transformation(OLCEK_MEMNUNIYET_KONUT),
dis = scale_transformation(OLCEK_MEMNUNIYET_SEMT),
js = scale_transformation(OLCEK_MEMNUNIYET_IS),
hhi_sat = scale_transformation(OLCEK_MEMNUNIYET_GELIR),
frs = scale_transformation(OLCEK_MEMNUNIYET_ARKADAS),
nes = scale_transformation(OLCEK_MEMNUNIYET_KOMSU),
sls = scale_transformation(OLCEK_MEMNUNIYET_SOS_HAYAT),
tul = scale_transformation(OLCEK_MEMNUNIYET_KISISEL_BKM),
# tuc = scale_transformation(OLCEK_MEMNUNIYET_IS_TRFK_ZMN),
psh = scale_transformation(GUVEN_EV),
pse = scale_transformation(GUVEN_CEVRE),
doh = scale_transformation(UMUT, 4, 1),
sw = scale_transformation(UMUT_BASAMAK, 1, 11),
sfsh = scale_transformation(OLCEK_MEMNUNIYET_GN_SAG),
sfss = scale_transformation(OLCEK_MEMNUNIYET_ASAYIS),
sfsj = scale_transformation(OLCEK_MEMNUNIYET_ADLI),
sfse = scale_transformation(OLCEK_MEMNUNIYET_EGITI),
sfss = scale_transformation(OLCEK_MEMNUNIYET_SGK),
sfst = scale_transformation(OLCEK_MEMNUNIYET_ULASIM),
sfsg = scale_transformation(ELEKTRO_HIZ),
lyp = ifelse(pmin(ISE_GIRDI, ISYERI_ACTI, GELIRI_ARTTI, TASARRUF_YAPTI, ARABA_ALDI, EV_ALDI, BORC_ODEDI, na.rm = TRUE) == 1, TRUE, FALSE),
lyn = ifelse(pmin(ISINI_KAYBETTI, IFLAS_ETTI, GELIRI_AZALDI, TASARRUFLARI_AZALDI, UCUZ_URUN, TATIL_KISTI, ARABA_SATTI, EV_SATTI, BORCLANDI, na.rm = TRUE) == 1, TRUE, FALSE),
lym = GOC_ETTI == 1,
fsp = pmax(CINSIYET_BASKI, MEDENI_DURUM_BASKI, YAS_BASKI, GELENEK_GORENEK, DINI_INANCDAN, SIYASI_GORUSTEN, MEMLEKETINDEN, ISINDEN_DOLAYI, KILIK_KIYAFET, ISSIZ_OLMA, GELIR_DUZEY_DURUM, na.rm = TRUE) > 3,
weight = HANE_FAKTOR